In [ ]:
# Q1: 1000人分の年齢のndarrayをnp.random.randintを使用して生成せよ。
# なお年齢の変数名はageとし、ageは0以上100以下とする。

# Q2: 1000人分の性別のndarrayをnp.random.randintを使用して生成せよ。
# なお性別の変数名はsexとし、sexは0, 1, 2の値を取るものとする。
# 0はLGBT、1は女性、2は男性とする。

# Q3: 所得は、以下のように決定されるとする。
#     0 ~ 15歳未満 >>> 0万円
#     15 ~ 23歳未満 >>> 0万円 ~ 100万円の間の整数。年齢によらずランダムに生成される。
#     23 ~ 50歳未満 >>> 200万円 × 年齢 + ε1
#                      ε1は[-20, -10, 0, 10, 20]のいずれかの値をランダムに取る確率変数。
#                      HINT: np.random.choiceを使用せよ。
#     23 ~ 50歳未満 >>> 200万円 × 年齢 + ε2
#                      ε2は[0, 10, 20]のいずれかの値をランダムに取る確率変数
#                      HINT: np.random.choiceを使用せよ。
#     51 ~         >>> -10万円 × 年齢 +1000 + ε2
#
#     また、性別が以下のように所得に影響を与えるものとする。
#     LGBTならば、-100万円
#     女性ならば、-50万円
#     男性ならば、100万円
#     （※ 所得に関しては、依然として男性が高い。）
#
#     なお、性別の効果で所得が負の値を取る結果となってしまうときは、所得は0になるように調整する。
#     HINT: np.maxを使用せよ。
#
#     これらの条件から1000人分の所得のndarrayを生成せよ。

# Q4: 生成された所得、年齢、性別のndarrayからpandas dataframeを生成せよ。

# Q5: Q4で生成されたdataframeを7:3の割合で分割せよ。scikit learnのtrain_test_split関数を使用せよ。
#     なお、7の割合のデータの変数名をtrain、3の割合のデータの変数名をtestとせよ。

# Q6: Q5で生成したtrain、testをカレントディレクトリにcsv形式で保存せよ。

In [ ]:
# Q1: 1000人分の年齢のndarrayをnp.random.randintを使用して生成せよ。
# なお年齢の変数名はageとし、ageは0以上100以下とする。

In [7]:
%%time
import numpy as np
age = np.random.randint(0,101,1000)
age

CPU times: user 557 µs, sys: 75 µs, total: 632 µs
Wall time: 572 µs


array([  9,  14,  21,  25,  94,  84,  68,  50, 100,  73,  34,   0,  31,
        98,  26,  67,  35,  34,   0,  86,  92,  29,  64,  89,  73,  89,
        92,  98,  32,  67,  22,  25,  68,  88,  47,  20,  39,  95,   2,
        44,  32,  45,   8,  21,  43,  29,  12,  70,  54,   0,  76,  84,
        40,  85,  32,  40,  75,  31,  56,  23,  25,  17,  95,  93,  79,
        55,  20,  73,  67,  47,  38,  20,  98,  54,  30,  67,  72,  35,
        98,  28,   5,  10,  17,  65,   3,  10,  34,  62,  29,  56,  55,
        12,  30,  28,  13,  24,  36,  64,  95,  50,  85,  86,  83,  77,
        87,  64,  50,  43,  36,  35,  98,  77,  26,  72,  53,   2,  20,
        53,  36,  26,   7,  58,  26,  75,   9,  88,  93,  45,  64,  20,
        63,  56,  17,  84,  43,  98,  66,   5,  28,  88,  82,  98,  71,
        92,  35,  53,  72,  40,   3,  98,  53,   7,   0,  32,  88,  38,
        23,  76,  10,   4,  35,  11,  52,  39,  14,  39,  93,  61,  55,
        24,  57,  51,  80,  57,  52,  30,  11,  78,  96,  95,  6

In [8]:
# Q2: 1000人分の性別のndarrayをnp.random.randintを使用して生成せよ。
# なお性別の変数名はsexとし、sexは0, 1, 2の値を取るものとする。
# 0はLGBT、1は女性、2は男性とする。

sex = np.random.randint(0,3,1000)
sex

array([0, 1, 0, 1, 0, 0, 1, 1, 2, 1, 0, 2, 0, 0, 2, 2, 1, 1, 2, 2, 2, 2,
       2, 1, 2, 1, 0, 0, 0, 2, 1, 0, 0, 0, 1, 0, 2, 0, 1, 1, 0, 2, 2, 0,
       0, 1, 0, 1, 0, 2, 2, 1, 2, 0, 1, 2, 2, 2, 0, 2, 1, 1, 2, 1, 1, 1,
       0, 2, 2, 0, 2, 0, 2, 2, 2, 2, 2, 1, 0, 0, 0, 2, 1, 0, 2, 0, 1, 2,
       1, 1, 2, 1, 2, 2, 2, 0, 1, 2, 0, 2, 1, 0, 0, 2, 2, 0, 2, 2, 1, 0,
       1, 2, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 2, 0, 1, 1, 0, 0, 2, 0, 2, 1,
       2, 0, 1, 2, 1, 1, 2, 0, 1, 1, 1, 1, 1, 0, 1, 0, 2, 2, 0, 0, 1, 0,
       2, 2, 2, 1, 1, 0, 1, 1, 2, 2, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0,
       2, 2, 0, 2, 0, 1, 1, 0, 2, 1, 1, 0, 2, 2, 2, 0, 1, 0, 1, 2, 0, 2,
       1, 2, 0, 1, 1, 0, 2, 1, 0, 1, 0, 2, 0, 2, 1, 2, 2, 2, 2, 2, 1, 2,
       2, 1, 1, 1, 0, 0, 0, 2, 1, 1, 1, 2, 1, 2, 2, 2, 2, 0, 1, 2, 1, 2,
       0, 2, 0, 1, 1, 1, 2, 1, 1, 1, 2, 1, 2, 1, 0, 0, 0, 1, 0, 1, 0, 2,
       1, 2, 1, 2, 0, 2, 0, 0, 0, 2, 2, 2, 0, 1, 0, 1, 2, 0, 2, 2, 2, 2,
       0, 0, 0, 0, 2, 0, 0, 1, 2, 0, 1, 1, 1, 1, 2,

In [22]:
dice.remove(50)

In [25]:
a = []
a.append(10)
a

[10]

In [14]:
dice = [-20, -10, 0, 10, 20]
dice2 = [0, 10, 20]
np.random.choice(dice)


20

In [51]:
dice2 = [0, 10, 20]

In [50]:
5 * 200 + np.random.choice(dice)

1020

In [69]:
a = [1,2,3]
b = [3,2,1]
c = np.add(a,b)
c

array([4, 4, 4])

In [30]:
np.random.choice(range(0,101))

67

In [ ]:
# Q3: 所得は、以下のように決定されるとする。
#     0 ~ 15歳未満 >>> 0万円
#     15 ~ 23歳未満 >>> 0万円 ~ 100万円の間の整数。年齢によらずランダムに生成される。
#     23 ~ 50歳未満 >>> 200万円 × 年齢 + ε1
#                      ε1は[-20, -10, 0, 10, 20]のいずれかの値をランダムに取る確率変数。
#                      HINT: np.random.choiceを使用せよ。
#     51 ~         >>> -10万円 × 年齢 +1000 + ε2
#                      ε2は[0, 10, 20]のいずれかの値をランダムに取る確率変数
#                      HINT: np.random.choiceを使用せよ。
#
#     また、性別が以下のように所得に影響を与えるものとする。
#     LGBTならば、-100万円
#     女性ならば、-50万円
#     男性ならば、100万円
#     （※ 所得に関しては、依然として男性が高い。）
#     0はLGBT、1は女性、2は男性とする。
#
#     なお、性別の効果で所得が負の値を取る結果となってしまうときは、所得は0になるように調整する。
#     HINT: np.maxを使用せよ。
#
#     これらの条件から1000人分の所得のndarrayを生成せよ。

In [84]:
income = []

dice = [-20, -10, 0, 10, 20]
dice2 = [0, 10, 20]

for x in age:
    if x < 15:
        income.append(0)
    elif 15 <= x < 23:
        income.append(np.random.choice(range(0,101)))
    elif 23 <= x < 50:
        income.append(x * 200 + np.random.choice(dice))
    else:
        income.append(x * -10 + 1000 + np.random.choice(dice2))  

In [87]:
income

[0,
 0,
 71,
 4990,
 80,
 160,
 340,
 510,
 20,
 280,
 6800,
 0,
 6200,
 30,
 5180,
 350,
 7020,
 6820,
 0,
 150,
 80,
 5780,
 380,
 120,
 290,
 110,
 100,
 30,
 6410,
 350,
 35,
 4980,
 340,
 130,
 9390,
 22,
 7810,
 70,
 0,
 8790,
 6400,
 8980,
 0,
 41,
 8610,
 5810,
 0,
 300,
 470,
 0,
 240,
 160,
 8010,
 150,
 6390,
 7980,
 260,
 6210,
 460,
 4580,
 5010,
 3,
 50,
 80,
 210,
 470,
 95,
 290,
 330,
 9390,
 7590,
 32,
 30,
 480,
 6020,
 330,
 300,
 7000,
 40,
 5620,
 0,
 0,
 3,
 350,
 0,
 0,
 6790,
 380,
 5790,
 460,
 470,
 0,
 6020,
 5580,
 0,
 4800,
 7190,
 380,
 50,
 520,
 160,
 140,
 170,
 230,
 130,
 380,
 520,
 8600,
 7210,
 7000,
 30,
 240,
 5220,
 300,
 480,
 0,
 13,
 490,
 7210,
 5220,
 0,
 440,
 5180,
 250,
 0,
 140,
 90,
 9020,
 370,
 92,
 390,
 450,
 69,
 180,
 8600,
 30,
 350,
 0,
 5590,
 120,
 190,
 40,
 300,
 80,
 7000,
 490,
 300,
 8000,
 0,
 40,
 490,
 0,
 0,
 6380,
 120,
 7580,
 4610,
 240,
 0,
 0,
 7020,
 0,
 480,
 7800,
 0,
 7780,
 80,
 400,
 470,
 4820,
 430,
 49

In [74]:
income_sex = []
for x in sex:
    if x == 0:
        income_sex.append(-100)
    elif x == 1:
        income_sex.append(-50)
    else: income_sex.append(100)

In [88]:
income_sex

[-100,
 -50,
 -100,
 -50,
 -100,
 -100,
 -50,
 -50,
 100,
 -50,
 -100,
 100,
 -100,
 -100,
 100,
 100,
 -50,
 -50,
 100,
 100,
 100,
 100,
 100,
 -50,
 100,
 -50,
 -100,
 -100,
 -100,
 100,
 -50,
 -100,
 -100,
 -100,
 -50,
 -100,
 100,
 -100,
 -50,
 -50,
 -100,
 100,
 100,
 -100,
 -100,
 -50,
 -100,
 -50,
 -100,
 100,
 100,
 -50,
 100,
 -100,
 -50,
 100,
 100,
 100,
 -100,
 100,
 -50,
 -50,
 100,
 -50,
 -50,
 -50,
 -100,
 100,
 100,
 -100,
 100,
 -100,
 100,
 100,
 100,
 100,
 100,
 -50,
 -100,
 -100,
 -100,
 100,
 -50,
 -100,
 100,
 -100,
 -50,
 100,
 -50,
 -50,
 100,
 -50,
 100,
 100,
 100,
 -100,
 -50,
 100,
 -100,
 100,
 -50,
 -100,
 -100,
 100,
 100,
 -100,
 100,
 100,
 -50,
 -100,
 -50,
 100,
 -50,
 -50,
 -50,
 -100,
 -50,
 -100,
 -100,
 -100,
 -100,
 -100,
 100,
 -100,
 -50,
 -50,
 -100,
 -100,
 100,
 -100,
 100,
 -50,
 100,
 -100,
 -50,
 100,
 -50,
 -50,
 100,
 -100,
 -50,
 -50,
 -50,
 -50,
 -50,
 -100,
 -50,
 -100,
 100,
 100,
 -100,
 -100,
 -50,
 -100,
 100,
 100,
 100,
 -50,

In [85]:
income_total = np.add(income, income_sex)

In [86]:
income_total

array([-100,  -50,  -29, 4940,  -20,   60,  290,  460,  120,  230, 6700,
        100, 6100,  -70, 5280,  450, 6970, 6770,  100,  250,  180, 5880,
        480,   70,  390,   60,    0,  -70, 6310,  450,  -15, 4880,  240,
         30, 9340,  -78, 7910,  -30,  -50, 8740, 6300, 9080,  100,  -59,
       8510, 5760, -100,  250,  370,  100,  340,  110, 8110,   50, 6340,
       8080,  360, 6310,  360, 4680, 4960,  -47,  150,   30,  160,  420,
         -5,  390,  430, 9290, 7690,  -68,  130,  580, 6120,  430,  400,
       6950,  -60, 5520, -100,  100,  -47,  250,  100, -100, 6740,  480,
       5740,  410,  570,  -50, 6120, 5680,  100, 4700, 7140,  480,  -50,
        620,  110,   40,   70,  330,  230,  280,  620, 8700, 7160, 6900,
        -20,  340, 5170,  250,  430, -100,  -37,  390, 7110, 5120, -100,
        340, 5280,  150,  -50,   90,  -10, 8920,  470,   -8,  490,  400,
        169,   80, 8550,  130,  300,  -50, 5690,   20,  140,  -10,  250,
         30, 6950,  390,  250, 7900,  100,  140,  3

In [95]:
len(income_total)

1000

In [103]:
income_total_positive = []
for x in income_total:
    if x < 0:
        income_total_positive.append(0)
    else:
        income_total_positive.append(x)

In [106]:
np.max(income_total)

9920

In [107]:
income_total

array([-100,  -50,  -29, 4940,  -20,   60,  290,  460,  120,  230, 6700,
        100, 6100,  -70, 5280,  450, 6970, 6770,  100,  250,  180, 5880,
        480,   70,  390,   60,    0,  -70, 6310,  450,  -15, 4880,  240,
         30, 9340,  -78, 7910,  -30,  -50, 8740, 6300, 9080,  100,  -59,
       8510, 5760, -100,  250,  370,  100,  340,  110, 8110,   50, 6340,
       8080,  360, 6310,  360, 4680, 4960,  -47,  150,   30,  160,  420,
         -5,  390,  430, 9290, 7690,  -68,  130,  580, 6120,  430,  400,
       6950,  -60, 5520, -100,  100,  -47,  250,  100, -100, 6740,  480,
       5740,  410,  570,  -50, 6120, 5680,  100, 4700, 7140,  480,  -50,
        620,  110,   40,   70,  330,  230,  280,  620, 8700, 7160, 6900,
        -20,  340, 5170,  250,  430, -100,  -37,  390, 7110, 5120, -100,
        340, 5280,  150,  -50,   90,  -10, 8920,  470,   -8,  490,  400,
        169,   80, 8550,  130,  300,  -50, 5690,   20,  140,  -10,  250,
         30, 6950,  390,  250, 7900,  100,  140,  3

In [108]:
np.max([-100, 0])

0

In [114]:
income_total_positive = []
for x in income_total:
    income_total_positive.append(np.max((x,0)))

In [115]:
income_total_positive

[0,
 0,
 0,
 4940,
 0,
 60,
 290,
 460,
 120,
 230,
 6700,
 100,
 6100,
 0,
 5280,
 450,
 6970,
 6770,
 100,
 250,
 180,
 5880,
 480,
 70,
 390,
 60,
 0,
 0,
 6310,
 450,
 0,
 4880,
 240,
 30,
 9340,
 0,
 7910,
 0,
 0,
 8740,
 6300,
 9080,
 100,
 0,
 8510,
 5760,
 0,
 250,
 370,
 100,
 340,
 110,
 8110,
 50,
 6340,
 8080,
 360,
 6310,
 360,
 4680,
 4960,
 0,
 150,
 30,
 160,
 420,
 0,
 390,
 430,
 9290,
 7690,
 0,
 130,
 580,
 6120,
 430,
 400,
 6950,
 0,
 5520,
 0,
 100,
 0,
 250,
 100,
 0,
 6740,
 480,
 5740,
 410,
 570,
 0,
 6120,
 5680,
 100,
 4700,
 7140,
 480,
 0,
 620,
 110,
 40,
 70,
 330,
 230,
 280,
 620,
 8700,
 7160,
 6900,
 0,
 340,
 5170,
 250,
 430,
 0,
 0,
 390,
 7110,
 5120,
 0,
 340,
 5280,
 150,
 0,
 90,
 0,
 8920,
 470,
 0,
 490,
 400,
 169,
 80,
 8550,
 130,
 300,
 0,
 5690,
 20,
 140,
 0,
 250,
 30,
 6950,
 390,
 250,
 7900,
 100,
 140,
 390,
 0,
 0,
 6280,
 220,
 7680,
 4710,
 190,
 0,
 0,
 6970,
 0,
 580,
 7900,
 0,
 7730,
 0,
 350,
 420,
 4720,
 380,
 390,
 100

In [120]:
[np.max((v,0)) for v in income_total]
import pandas as pd

In [118]:
# Q4: 生成された所得、年齢、性別のndarrayからpandas dataframeを生成せよ。

In [140]:
population_data = pd.DataFrame({"Age": age, "Sex":sex, "Income":income_total_positive})

In [141]:
population_data

Age  Sex  Income
0      9    0       0
1     14    1       0
2     21    0       0
3     25    1    4940
4     94    0       0
..   ...  ...     ...
995   50    0     420
996   35    2    7100
997   91    2     190
998   16    2     175
999   48    0    9490

[1000 rows x 3 columns]

In [ ]:
# Q5: Q4で生成されたdataframeを7:3の割合で分割せよ。scikit learnのtrain_test_split関数を使用せよ。
# なお、7の割合のデータの変数名をtrain、3の割合のデータの変数名をtestとせよ。
# Q6: Q5で生成したtrain、testをカレントディレクトリにcsv形式で保存せよ。

In [142]:
from sklearn.model_selection import train_test_split

In [143]:
train_test_split(population_data, test_size=0.3)

[     Age  Sex  Income
 957    6    0       0
 909    3    2     100
 777   15    0       0
 875   79    2     330
 452   39    2    7910
 ..   ...  ...     ...
 656   56    2     550
 626   82    2     300
 393   32    1    6330
 144   35    1    6950
 871   17    2     125
 
 [700 rows x 3 columns],
      Age  Sex  Income
 148    3    2     100
 319    4    1       0
 846   71    1     250
 655   22    1      12
 976   41    0    8090
 ..   ...  ...     ...
 776   20    2     114
 527   23    1    4530
 344   26    2    5310
 233   85    2     250
 812   80    0     110
 
 [300 rows x 3 columns]]

In [155]:
train,test = train_test_split(population_data, test_size=0.3)

In [148]:
atsushiname,leoname = ["atushi", "leo"]

In [149]:
atsushiname

'atushi'

In [150]:
leoname

'leo'

In [156]:
train

Age  Sex  Income
267    7    2     100
394   82    0     100
719   83    1     140
445   55    0     370
556   76    1     190
..   ...  ...     ...
152    0    1       0
768   38    1    7570
370   25    0    4920
566   67    2     450
762   68    0     220

[700 rows x 3 columns]

In [157]:
test

Age  Sex  Income
751    1    2     100
925   47    0    9320
257   31    0    6120
473   54    2     570
748   59    0     310
..   ...  ...     ...
973   39    1    7760
208   64    0     270
12    31    0    6100
636   80    0     120
900   14    2     100

[300 rows x 3 columns]

In [163]:
# Q6: Q5で生成したtrain、testをカレントディレクトリにcsv形式で保存せよ。
train.to_csv('train.csv')

In [160]:
%ls

20210803_q&a_matsumura_v2.ipynb  Test1.ipynb
Test 2.0.ipynb                   train


In [164]:
test.to_csv('test.csv')

In [165]:
%ls

20210803_q&a_matsumura_v2.ipynb  test.csv
Test 2.0.ipynb                   train
Test1.ipynb                      train.csv
test


In [166]:
%rm train

In [167]:
%ls

20210803_q&a_matsumura_v2.ipynb  test
Test 2.0.ipynb                   test.csv
Test1.ipynb                      train.csv


In [168]:
%rm test

In [169]:
%ls

20210803_q&a_matsumura_v2.ipynb  test.csv
Test 2.0.ipynb                   train.csv
Test1.ipynb
